server:
  port: 8088
  tomcat:
    max-http-post-size: -1

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: shopping
  redis:
    database: 0
    host: 192.168.1.11
    port: 6379
    timeout: 5000
    lettuce:
      pool:
        max-active: 32
        max-wait: -1
        max-idle: 16
        min-idle: 8
    password: 123456
  datasource:
    url: jdbc:mysql://192.168.1.11:3306/shopping?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 211114
    type: com.alibaba.druid.pool.DruidDataSource
    # 配置druid数据库连接池---------------------------------------
    initialSize: 5        # 初始化大小，最小，最大
    minIdle: 5
    maxActive: 20
    maxWait: 60000        # 配置获取连接等待超时的时间
    timeBetweenEvictionRunsMillis: 60000  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    minEvictableIdleTimeMillis: 300000    # 配置一个连接在池中最小生存的时间，单位是毫秒
    validationQuery: SELECT 'x'           # 校验SQL，Oracle配置 spring.datasource.validationQuery=SELECT 1 FROM DUAL，如果不配validationQuery项，则下面三项配置无用
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true   # 打开PSCache，并且指定每个连接上PSCache的大小
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j       # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000  # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    useGlobalDataSourceStat: true  # 合并多个DruidDataSource的监控数据
  # 设置上传文件大小
  servlet:
    multipart:
      enabled: true
      max-file-size: 524288000
      max-request-size: 524288000

# 配置mybatis-plus的xml和bean的目录
mybatis-plus:
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:  #逻辑删除配置
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
    refresh-mapper: true # 刷新mapper 调试神器

salt: 123456
strength: 16

file:
  imageFilePath: D:/upload/images/ #图片路径
  docFilePath: /data/sale/upload/doc/ # 文档路径
  contractTemplatePdfPath: /data/sale/upload/template/  #临时合同pdf存放路径
  contractPdfPath: /data/sale/upload/contract/  #正式合同pdf存放路径
  loadBillPdfPath: /data/sale/upload/loadBill/  #提货单存放路径
  maxFileSize: 524288000 #文件大小限制，这里是500M

